### ISSUE TITLE
[meta] Changelog Automation

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/client_golang#1546]
Thanks to @SachinSahu431, we advanced a lot in our project of changelog automation :)

We can't say it's complete though, since we haven't battle-tested the automation with a real release, and we also found a few things we'd like to clean up.

This issue is a meta issue, collecting all things we still want to do before declaring that "Changelog automation is completed".

---

- [ ] #1547
- [ ] Do not comment on PR if the description is ok.
- [ ] #1548
- [ ] Go through all PR's merged since last release and add appropriate label
- [ ] Review and merge https://github.com/prometheus/client_golang/pull/1519
- [ ] Test automation in test branch

--- 

In a very far future, we'd like to move this work to promu. Ideally continuing the work done in https://github.com/prometheus/promu/pull/170

**Comment by bwplotka** [comment]
Don't think it's completed 
![image](https://github.com/user-attachments/assets/21833f06-6b90-4ab8-b3c8-3bb7e72459cb)

Did you mean to close as not planned @ArthurSens ?
